spring:
  application:
    name: hermes
  jackson:
    propertyNamingStrategy: SNAKE_CASE
  docker:
    compose:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hermesdb
    password: sa
    username: Access123
  h2:
    console:
      enabled: 'true'
resilience4j.retry:
  instances:
    notificationRetry:
      maxAttempts: 3
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
          - java.lang.RuntimeException
resilience4j.circuitbreaker:
  instances:
    notificationBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

