spring:
  application:
    name: hermes
  jackson:
    propertyNamingStrategy: SNAKE_CASE
  docker:
    compose:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hermesdb
    password: hermesdbm
    username: A_Sup3rS3cr3tP@$$word!
  h2:
    console:
      enabled: 'true'
resilience4j.retry:
  instances:
    notificationRetry:
      maxAttempts: 3
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
          - java.lang.RuntimeException
resilience4j.circuitbreaker:
  instances:
    notificationBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
